/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo1;

/**
 *
 * @author User
 */
public class HomeMdi extends javax.swing.JFrame {

    /**
     * Creates new form HomeMdi
     */
    public HomeMdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ven_de = new javax.swing.JMenuItem();
        emp_de = new javax.swing.JMenuItem();
        cus_de = new javax.swing.JMenuItem();
        logoff = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        food_ma = new javax.swing.JMenuItem();
        billing = new javax.swing.JMenuItem();
        cus_acc = new javax.swing.JMenuItem();
        emp_acc = new javax.swing.JMenuItem();
        vendor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        food = new javax.swing.JMenuItem();
        drink = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        order_food = new javax.swing.JMenuItem();
        status = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cus_report = new javax.swing.JMenuItem();
        emp_report = new javax.swing.JMenuItem();
        vendor_report = new javax.swing.JMenuItem();
        payment_report = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/images/des95.jpg"))); // NOI18N

        fileMenu.setMnemonic('f');
        fileMenu.setText("Home");

        ven_de.setMnemonic('o');
        ven_de.setText("Vendo details");
        ven_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ven_deActionPerformed(evt);
            }
        });
        fileMenu.add(ven_de);

        emp_de.setMnemonic('s');
        emp_de.setText("Employee Details");
        emp_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_deActionPerformed(evt);
            }
        });
        fileMenu.add(emp_de);

        cus_de.setMnemonic('a');
        cus_de.setText("Customers Details");
        cus_de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_deActionPerformed(evt);
            }
        });
        fileMenu.add(cus_de);

        logoff.setMnemonic('x');
        logoff.setText("Log Off");
        logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffActionPerformed(evt);
            }
        });
        fileMenu.add(logoff);

        jMenuItem1.setText("Canteen_Details");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Account");

        food_ma.setText("Food Manager");
        food_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_maActionPerformed(evt);
            }
        });
        editMenu.add(food_ma);

        billing.setMnemonic('t');
        billing.setText("Billing");
        billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingActionPerformed(evt);
            }
        });
        editMenu.add(billing);

        cus_acc.setMnemonic('y');
        cus_acc.setText("Customers_Acc");
        cus_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_accActionPerformed(evt);
            }
        });
        editMenu.add(cus_acc);

        emp_acc.setMnemonic('d');
        emp_acc.setText("Employees_Acc");
        emp_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_accActionPerformed(evt);
            }
        });
        editMenu.add(emp_acc);

        vendor.setText("Vendor_Acc");
        editMenu.add(vendor);

        menuBar.add(editMenu);

        jMenu2.setText("Product");

        food.setText("Food");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });
        jMenu2.add(food);

        drink.setText("Drink");
        drink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkActionPerformed(evt);
            }
        });
        jMenu2.add(drink);

        menuBar.add(jMenu2);

        jMenu3.setText("Kitchen");

        order_food.setText("Order_Food");
        order_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_foodActionPerformed(evt);
            }
        });
        jMenu3.add(order_food);

        status.setText("Status");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jMenu3.add(status);

        menuBar.add(jMenu3);

        jMenu4.setText("Report");

        cus_report.setText("Customers");
        cus_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cus_reportActionPerformed(evt);
            }
        });
        jMenu4.add(cus_report);

        emp_report.setText("Employees");
        jMenu4.add(emp_report);

        vendor_report.setText("Vendor");
        jMenu4.add(vendor_report);

        payment_report.setText("Payment");
        jMenu4.add(payment_report);

        menuBar.add(jMenu4);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logoffActionPerformed

    private void ven_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ven_deActionPerformed
        // TODO add your handling code here:
        vendor_details ve=new vendor_details();
        ve.show();
    }//GEN-LAST:event_ven_deActionPerformed

    private void drinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkActionPerformed
        // TODO add your handling code here:
        Pro_Drink pro_dr=new Pro_Drink();
        pro_dr.show();
        
    }//GEN-LAST:event_drinkActionPerformed

    private void cus_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_accActionPerformed
        // TODO add your handling code here:
        customer_Acc Caac=new customer_Acc();
        Caac.show();
        
    }//GEN-LAST:event_cus_accActionPerformed

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
        // TODO add your handling code here:
        Bill_pay bill;
        bill = new Bill_pay();
        bill.show();
        
    }//GEN-LAST:event_billingActionPerformed

    private void cus_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_reportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cus_reportActionPerformed

    private void emp_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_deActionPerformed
        // TODO add your handling code here:
        employee_details empd=new employee_details();
        empd.show();
        
    }//GEN-LAST:event_emp_deActionPerformed

    private void cus_deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cus_deActionPerformed
        // TODO add your handling code here:
        customer_details cusd=new customer_details();
        cusd.show();
        
    }//GEN-LAST:event_cus_deActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
     canteen_details cand=new canteen_details();
     cand.show();
     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void food_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_maActionPerformed
        // TODO add your handling code here:
        Food_m food_m=new Food_m();
        food_m.show();
    }//GEN-LAST:event_food_maActionPerformed

    private void order_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_foodActionPerformed
        // TODO add your handling code here:
        //order_food ord=new order_food();
        order_food o_f =new order_food();
        o_f.show();
        
        
    }//GEN-LAST:event_order_foodActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
        Status st=new Status();
        st.show();
        
    }//GEN-LAST:event_statusActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        // TODO add your handling code here:
        por_food pro=new por_food();
        pro.show();
        
    }//GEN-LAST:event_foodActionPerformed

    private void emp_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_accActionPerformed
        // TODO add your handling code here:
        Emp_Acc EAcc=new Emp_Acc();
        EAcc.show();
      
    }//GEN-LAST:event_emp_accActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem billing;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cus_acc;
    private javax.swing.JMenuItem cus_de;
    private javax.swing.JMenuItem cus_report;
    private javax.swing.JMenuItem drink;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem emp_acc;
    private javax.swing.JMenuItem emp_de;
    private javax.swing.JMenuItem emp_report;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem food;
    private javax.swing.JMenuItem food_ma;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem logoff;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem order_food;
    private javax.swing.JMenuItem payment_report;
    private javax.swing.JMenuItem status;
    private javax.swing.JMenuItem ven_de;
    private javax.swing.JMenuItem vendor;
    private javax.swing.JMenuItem vendor_report;
    // End of variables declaration//GEN-END:variables

}
